name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Install rustfmt
        run: rustup component add rustfmt
  
      - name: Install clippy
        run: rustup component add clippy

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check code formatting
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check with Clippy
        uses: actions-rs/clippy-check@v1

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: cargo test
